POST http://localhost:9090/api/v3/movie
Content-Type: application/json

{
    "title": "Dune",
    "path": "/movies/Dune (2021)",
    "rootFolderPath": "/movies",
    "monitored": true,
    "qualityProfileId": 1,
    "minimumAvailability": "released",
    "tmdbId": 4386
}
###

GET http://localhost:9090/api/v3/movie?monitored=true
Content-Type: application/json
